### ISSUE TITLE
Content resolver is treating non-default module streams as if they were enabled

### ISSUE THREAD

**Issue by sgallagher** [minimization/content-resolver#36]
As seen in https://tiny.distro.builders/workload--sst_cs_infra_services-subversion-eln--fedora-empty-base--repository-fedora-eln--aarch64.html
```
 Problem 1: conflicting requests
  - nothing provides python(abi) = 3.9 needed by python3-subversion-1.14.0-6.module_eln+13718+74d85072.aarch64
 Problem 2: package subversion-perl-1.14.0-6.module_eln+13718+74d85072.aarch64 requires perl(:MODULE_COMPAT_5.32.1), but none of the providers can be installed
  - package subversion-perl-1.14.0-6.module_eln+13718+74d85072.aarch64 requires libperl.so.5.32()(64bit), but none of the providers can be installed
  - conflicting requests
  - package perl-libs-4:5.32.1-477.module_eln+13903+73720ee2.aarch64 is filtered out by modular filtering
```

**Comment by asamalik** [comment]
The workload explicitly enables the `subversion:1.14` module. But let me see why it's failing.

**Comment by asamalik** [comment]
Looks like the packages in the module require a specific Python version, but the module itself doesn't specify any dependencies. https://src.fedoraproject.org/modules/subversion/blob/1.14/f/subversion.yaml#_13

I believe Content Resolver behaves correctly here. And by Content Resolver I mean DNF, because it just calls DNF to be compatible with how people see stuff.

So this seems to be a packaging problem.

**Comment by yselkowitz** [comment]
Modularity has been dropped completely from RHEL 10 and hence from Content Resolver.
